create table if not exists todos (
  id bigint generated by default as identity primary key,
  title text not null,
  is_complete boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);